-- ============================================================================
-- Insertar productos de materia prima
-- PL-CAL-010 - Plan de Muestreo Materia Prima
-- ============================================================================

-- Materia Fresca
INSERT INTO lab_microbiologia.materia_prima_productos (nombre) VALUES
    ('Ajo'),
    ('Apio'),
    ('Brevas'),
    ('Carne Molida'),
    ('Coliflor'),
    ('Crema de leche 33%'),
    ('Fresa'),
    ('Habichuelas'),
    ('Mora'),
    ('Pimentón'),
    ('Piña'),
    ('Zanahoria'),
    ('Cebolla cabezona');

-- Insumos Proveedores
INSERT INTO lab_microbiologia.materia_prima_productos (nombre) VALUES
    ('Aceite de soya'),
    ('Aceite Esencial de Cebolla'),
    ('Acido Ascórbico'),
    ('Acido Citrico'),
    ('Aquagel'),
    ('Aji Molido'),
    ('Ajo en polvo'),
    ('Ajo sabor liquido'),
    ('Ajonjoli'),
    ('Albahaca en escamas'),
    ('Almidon Candamyl'),
    ('Almidon Mira Thik 603'),
    ('Almidon Snowflake 6704'),
    ('Antiespumante'),
    ('Azúcar'),
    ('Benzoato de sodio'),
    ('BHT (Antioxidante)'),
    ('Canela en astillas'),
    ('Cebolla en polvo'),
    ('Cebolla sabor liquido'),
    ('Clavo entero'),
    ('Cloruro de Calcio'),
    ('CMC'),
    ('Color amarillo tartrazina'),
    ('Color caramelo AP -2000'),
    ('Color caramelo (CS) para Vinagres'),
    ('Color Curcuma'),
    ('Color Rojo # 40'),
    ('Color rojo ponceau 4R'),
    ('Color verde menta'),
    ('Comino polvo'),
    ('Cremor Tartaro'),
    ('Curcuma en polvo'),
    ('Curry en polvo'),
    ('Dextrosa Monohidratada'),
    ('EDTA'),
    ('Etil vainilla'),
    ('Esencia de ajo'),
    ('Esencia de vainilla'),
    ('EXLV (Extracto levadura)'),
    ('Fecula'),
    ('Garbanzo'),
    ('Glucosa'),
    ('Glutamato'),
    ('Goma Xanthan'),
    ('Grasa vegetal Hidrolizada'),
    ('Harina de mostaza'),
    ('Humo liquido'),
    ('Jengibre en polvo'),
    ('Lactasa'),
    ('Laurel escamas'),
    ('Leche en polvo'),
    ('Lecitina de soya'),
    ('Miel de abeja'),
    ('Natamicina'),
    ('Oregano en escamas'),
    ('Oregano en polvo'),
    ('Panela'),
    ('Paprika en polvo'),
    ('Pectinas baja (105)'),
    ('Perejil en escamas'),
    ('Pimienta'),
    ('Polidextrosa'),
    ('Propilenglicol'),
    ('Queso tipo parmesano'),
    ('Sabor BBQ'),
    ('Sabor Brandy Liquido'),
    ('Sabor Camarón'),
    ('Sabor Cereza marraschino'),
    ('Sabor Cheddar'),
    ('Saborizante Vainilla (Callizo)'),
    ('Sabor Salsa Inglesa'),
    ('Sabor Ketchup'),
    ('Sabor Mantequilla'),
    ('Sabor Miel'),
    ('Sidra sabor liquido'),
    ('Sabor Piña natural'),
    ('Sabor Pollo'),
    ('Sabor tocineta polvo'),
    ('Sabor Tomate'),
    ('Sal Refinada'),
    ('Salsa aji (Maquila Ají 82)'),
    ('Sazonador Cheddar'),
    ('Sorbato de Potasio'),
    ('Tomillo en escamas'),
    ('Tomillo molido'),
    ('Uva sabor liquido'),
    ('Vainilla Aroma (Lucta)'),
    ('Vainilla blanca sabor liquido (Picolinni)'),
    ('Vinagre al 11%'),
    ('Yema de huevo Pasteurizada');

-- Insumos Proveedores Importados
INSERT INTO lab_microbiologia.materia_prima_productos (nombre) VALUES
    ('Aceite de Oliva'),
    ('Aceitunas deshuesadas'),
    ('Aceitunas gordal'),
    ('Aceitunas Manzanilla'),
    ('Aceitunas Moradas'),
    ('Aceitunas Negras'),
    ('Aceitunas Rellenas'),
    ('Aceitunas rodajas'),
    ('Alcaparras'),
    ('Almendra'),
    ('Arveja seca'),
    ('Cebollitas'),
    ('Cerezas Expofrugal'),
    ('Cerezas Kuminiano'),
    ('Ciruelas Con y Sin semilla Pietrelli'),
    ('Deltarome (proteina)'),
    ('Jalapeños'),
    ('Pasta de Tomate'),
    ('Pepinillos 1era'),
    ('Pepinillos 2da, 3era, 4ta'),
    ('Proteina JE'),
    ('Uvas pasas (Santis Frut)'),
    ('Uvas pasas (Vizcaino)'),
    ('Vinagre Balsamico');
