import './globals.css'
import '@/lib/react-dom-patch' // Aplicar patch para React DOM
import { AuthProvider } from '@/contexts/auth-context'
import AuthLayoutClient from '@/components/auth-layout-client'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Area de calidad',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-body antialiased">
        <AuthProvider>
          <AuthLayoutClient>
            {children}
            <Toaster />
          </AuthLayoutClient>
        </AuthProvider>
      </body>
    </html>
  )
}
